"""
Loan Approval Prediction — Streamlit Web App
=============================================

Deploys the Logistic Regression pipeline (88.5% test accuracy) from the
training notebook behind a 100% native Streamlit UI (no custom CSS/HTML/JS).

Expected files next to this script
----------------------------------
* model.pkl   -> pickled ``LogisticRegression(max_iter=10000)``
* scaler.pkl  -> pickled ``StandardScaler`` fitted during training

If either artifact is missing (or unpicklable), the app transparently trains
a FALLBACK Logistic Regression model on synthetic data so it runs out of the
box. A warning is shown in the sidebar whenever fallback mode is active.

Feature schema
--------------
The training notebook produced 25 X columns (``Applicant_ID`` was left in X).
Per the deployment spec, ``Applicant_ID`` is EXCLUDED here, so the app builds
the remaining 24 features in the exact column order pandas produced. If a
supplied model.pkl/scaler.pkl still expects 25 features, a neutral
``Applicant_ID`` column is injected automatically (scaled to zero), so both
artifact variants work.

Run
---
    streamlit run app.py
"""

from __future__ import annotations

import os
import pickle
from typing import Any

import numpy as np
import pandas as pd
import streamlit as st
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# ---------------------------------------------------------------------------
# 1. Constants — mirror the training notebook exactly
# ---------------------------------------------------------------------------
MODEL_FILE = "model.pkl"
SCALER_FILE = "scaler.pkl"

MODEL_METADATA = {
    "Model": "Logistic Regression",
    "Accuracy": "88.5%",
    "Scaler": "StandardScaler",
}

# LabelEncoder maps categories in sorted (alphabetical) order — identical to
# the ``LabelEncoder`` calls in the training notebook.
EDUCATION_MAP = {"Graduate": 0, "Not Graduate": 1, "Post Graduate": 2}
EMPLOYER_MAP = {
    "Government": 0,
    "MNC": 1,
    "Private": 2,
    "Self-Employed": 3,
    "Unemployed": 4,
}
DEPENDENTS_MAP = {"0": 0.0, "1": 1.0, "2": 2.0, "3": 3.0, "4+": 4.0}

# Categoricals one-hot encoded with pd.get_dummies(drop_first=True) during
# training. drop_first removes the alphabetically-first (base) category:
#   Employment_Status -> base 'Contract'   | Marital_Status -> base 'Married'
#   Loan_Purpose      -> base 'Business'   | Property_Area  -> base 'Rural'
#   Gender            -> base 'Female'
OHE_COLUMNS = [
    "Employment_Status",
    "Marital_Status",
    "Loan_Purpose",
    "Property_Area",
    "Gender",
]

# The 24 production features (Applicant_ID intentionally excluded), listed in
# the EXACT column order generated by the training pipeline.
FEATURE_COLUMNS = [
    "Applicant_Income",
    "Coapplicant_Income",
    "Employment_Status_Salaried",
    "Employment_Status_Self-employed",
    "Employment_Status_Unemployed",
    "Age",
    "Marital_Status_Single",
    "Dependents",
    "Credit_Score",
    "Existing_Loans",
    "DTI_Ratio",
    "Savings",
    "Collateral_Value",
    "Loan_Amount",
    "Loan_Term",
    "Loan_Purpose_Car",
    "Loan_Purpose_Education",
    "Loan_Purpose_Home",
    "Loan_Purpose_Personal",
    "Property_Area_Semiurban",
    "Property_Area_Urban",
    "Education_Level",
    "Gender_Male",
    "Employer_Category",
]

# Widget option lists
LOAN_TERM_OPTIONS = [12, 24, 36, 48, 60, 120, 180, 240, 360]
DEPENDENTS_OPTIONS = list(DEPENDENTS_MAP.keys())
GENDER_OPTIONS = ["Female", "Male"]
MARITAL_OPTIONS = ["Single", "Married"]
EMPLOYMENT_OPTIONS = ["Salaried", "Self-employed", "Contract", "Unemployed"]
PURPOSE_OPTIONS = ["Personal", "Car", "Business", "Home", "Education"]
AREA_OPTIONS = ["Urban", "Semiurban", "Rural"]
EDUCATION_OPTIONS = ["Not Graduate", "Graduate", "Post Graduate"]
EMPLOYER_OPTIONS = ["Unemployed", "Private", "Government", "MNC", "Self-Employed"]

FALLBACK_SEED = 42
APPROVAL_THRESHOLD = 0.5


# ---------------------------------------------------------------------------
# 2. Preprocessing — identical logic to the training notebook
# ---------------------------------------------------------------------------
def transform_raw_frame(raw: pd.DataFrame) -> pd.DataFrame:
    """Apply the notebook's preprocessing to a raw input frame.

    Ordinal encoding (Education_Level, Employer_Category) + one-hot encoding
    equivalent to ``pd.get_dummies(..., drop_first=True)``. Reindexing against
    ``FEATURE_COLUMNS`` enforces the exact training schema and implicitly drops
    the base categories — this is also safe for single-row prediction frames,
    where a naive ``drop_first=True`` call would misbehave.
    """
    df = raw.copy()
    df["Education_Level"] = df["Education_Level"].map(EDUCATION_MAP).astype(float)
    df["Employer_Category"] = df["Employer_Category"].map(EMPLOYER_MAP).astype(float)

    dummies = pd.get_dummies(df[OHE_COLUMNS], dtype=int)
    df = pd.concat([df.drop(columns=OHE_COLUMNS), dummies], axis=1)
    return df.reindex(columns=FEATURE_COLUMNS, fill_value=0)


def _neutralize_applicant_id(df: pd.DataFrame, scaler: StandardScaler) -> None:
    """Fill an injected Applicant_ID with its training mean so it scales to 0."""
    if "Applicant_ID" not in df.columns:
        return
    names = list(getattr(scaler, "feature_names_in_", []))
    mean = getattr(scaler, "mean_", None)
    if names and mean is not None and "Applicant_ID" in names:
        df["Applicant_ID"] = float(mean[names.index("Applicant_ID")])
    else:
        df["Applicant_ID"] = 0.0


def align_features(x: pd.DataFrame, scaler: StandardScaler) -> pd.DataFrame:
    """Align the app's 24-feature frame with the schema the scaler expects.

    Handles both artifact variants:
    * 24 features -> Applicant_ID excluded (this app's canonical schema)
    * 25 features -> notebook schema; a neutral Applicant_ID is injected
    """
    expected = getattr(scaler, "feature_names_in_", None)
    if expected is not None:
        aligned = x.reindex(columns=list(expected), fill_value=0.0)
        _neutralize_applicant_id(aligned, scaler)
        return aligned

    n_expected = int(getattr(scaler, "n_features_in_", x.shape[1]))
    if n_expected == x.shape[1]:
        return x
    if n_expected == len(FEATURE_COLUMNS) + 1:  # notebook kept Applicant_ID
        aligned = x.copy()
        aligned.insert(0, "Applicant_ID", 0.0)
        return aligned
    raise ValueError(
        f"Feature mismatch: app builds {x.shape[1]} features, "
        f"scaler expects {n_expected}."
    )


# ---------------------------------------------------------------------------
# 3. Fallback model — synthetic data so the app runs out of the box
# ---------------------------------------------------------------------------
def generate_synthetic_dataset(n_rows: int = 2000, seed: int = FALLBACK_SEED) -> pd.DataFrame:
    """Deterministic synthetic dataset mimicking loan_approval_data.csv."""
    rng = np.random.default_rng(seed)

    applicant_income = np.round(rng.lognormal(mean=9.0, sigma=0.55, size=n_rows)).clip(1_500, 60_000)
    coapplicant_income = np.round(rng.gamma(shape=2.0, scale=1_100, size=n_rows)).clip(0, 25_000)
    age = rng.integers(21, 66, size=n_rows).astype(float)
    credit_score = np.round(rng.normal(loc=645, scale=95, size=n_rows)).clip(300, 850)
    existing_loans = rng.choice(
        [0.0, 1.0, 2.0, 3.0, 4.0, 5.0], size=n_rows, p=[0.22, 0.30, 0.22, 0.14, 0.08, 0.04]
    )
    dti_ratio = np.round(rng.beta(a=2.2, b=4.5, size=n_rows) * 0.85 + 0.05, 2)
    savings = np.round(rng.gamma(shape=2.0, scale=2_800, size=n_rows)).clip(0, 80_000)
    collateral_value = np.round(rng.gamma(shape=2.4, scale=5_500, size=n_rows)).clip(0, 150_000)
    loan_amount = np.round(rng.gamma(shape=2.2, scale=4_200, size=n_rows)).clip(2_000, 80_000)
    loan_term = rng.choice(LOAN_TERM_OPTIONS, size=n_rows).astype(float)
    dependents = rng.choice([0.0, 1.0, 2.0, 3.0], size=n_rows, p=[0.35, 0.30, 0.25, 0.10])
    gender = rng.choice(GENDER_OPTIONS, size=n_rows, p=[0.35, 0.65])
    marital_status = rng.choice(MARITAL_OPTIONS, size=n_rows, p=[0.45, 0.55])
    employment_status = rng.choice(EMPLOYMENT_OPTIONS, size=n_rows, p=[0.50, 0.25, 0.15, 0.10])
    loan_purpose = rng.choice(PURPOSE_OPTIONS, size=n_rows, p=[0.30, 0.25, 0.15, 0.15, 0.15])
    property_area = rng.choice(AREA_OPTIONS, size=n_rows, p=[0.40, 0.40, 0.20])
    education_level = rng.choice(EDUCATION_OPTIONS, size=n_rows, p=[0.30, 0.50, 0.20])
    employer_category = rng.choice(EMPLOYER_OPTIONS, size=n_rows, p=[0.10, 0.40, 0.20, 0.20, 0.10])

    # Rule-based approval signal (credit quality, leverage, collateral, stability)
    total_income = applicant_income + coapplicant_income
    collateral_coverage = np.clip(
        (collateral_value - loan_amount) / np.maximum(loan_amount, 1.0), -1.0, 2.0
    )
    employment_boost = np.select(
        [
            employment_status == "Salaried",
            employment_status == "Self-employed",
            employment_status == "Contract",
        ],
        [0.45, 0.15, 0.0],
        default=-1.1,
    )
    education_boost = np.select(
        [education_level == "Post Graduate", education_level == "Graduate"],
        [0.30, 0.15],
        default=0.0,
    )
    logit = (
        1.9 * (credit_score - 640) / 100
        - 2.6 * (dti_ratio - 0.35) / 0.15
        + 1.1 * (np.log1p(total_income) - 9.4)
        + 0.6 * (np.log1p(savings) - 7.8)
        + 0.8 * collateral_coverage
        - 0.30 * existing_loans
        - 0.15 * dependents
        + employment_boost
        + education_boost
        + rng.normal(0.0, 0.65, size=n_rows)
    )
    approval_probability = 1.0 / (1.0 + np.exp(-logit))
    loan_approved = (rng.random(n_rows) < approval_probability).astype(int)

    return pd.DataFrame(
        {
            "Applicant_Income": applicant_income,
            "Coapplicant_Income": coapplicant_income,
            "Employment_Status": employment_status,
            "Age": age,
            "Marital_Status": marital_status,
            "Dependents": dependents,
            "Credit_Score": credit_score,
            "Existing_Loans": existing_loans,
            "DTI_Ratio": dti_ratio,
            "Savings": savings,
            "Collateral_Value": collateral_value,
            "Loan_Amount": loan_amount,
            "Loan_Term": loan_term,
            "Loan_Purpose": loan_purpose,
            "Property_Area": property_area,
            "Education_Level": education_level,
            "Gender": gender,
            "Employer_Category": employer_category,
            "Loan_Approved": loan_approved,
        }
    )


def build_fallback_artifacts(n_rows: int = 2000) -> tuple[LogisticRegression, StandardScaler]:
    """Train the fallback Logistic Regression + StandardScaler pair."""
    data = generate_synthetic_dataset(n_rows)
    x = transform_raw_frame(data.drop(columns=["Loan_Approved"]))
    y = data["Loan_Approved"].astype(int)

    scaler = StandardScaler().fit(x)
    model = LogisticRegression(max_iter=10_000).fit(scaler.transform(x), y)
    return model, scaler


# ---------------------------------------------------------------------------
# 4. Artifact loading + prediction
# ---------------------------------------------------------------------------
@st.cache_resource(show_spinner="Loading model artifacts...")
def load_artifacts() -> tuple[Any, Any, str, str | None]:
    """Return ``(model, scaler, source, warning)``.

    ``source`` is either ``"trained"`` (real pickles loaded) or ``"fallback"``
    (synthetic model trained on the fly).
    """
    if os.path.exists(MODEL_FILE) and os.path.exists(SCALER_FILE):
        try:
            with open(MODEL_FILE, "rb") as fh:
                model = pickle.load(fh)
            with open(SCALER_FILE, "rb") as fh:
                scaler = pickle.load(fh)
            return model, scaler, "trained", None
        except Exception as exc:  # corrupt / incompatible pickles
            model, scaler = build_fallback_artifacts()
            warning = (
                f"Could not load the pickled artifacts ({exc}). "
                "A fallback model trained on synthetic data is active."
            )
            return model, scaler, "fallback", warning

    model, scaler = build_fallback_artifacts()
    missing = " and ".join(f for f in (MODEL_FILE, SCALER_FILE) if not os.path.exists(f))
    warning = (
        f"{missing} not found — a fallback model was trained on synthetic data so the "
        "app runs out of the box. Drop your real model.pkl + scaler.pkl next to app.py "
        "for production predictions."
    )
    return model, scaler, "fallback", warning


def predict_approval(
    model: Any, scaler: StandardScaler, x: pd.DataFrame
) -> tuple[bool, float]:
    """Scale the feature vector and return ``(approved, approval_probability)``."""
    x_aligned = align_features(x, scaler)
    x_scaled = scaler.transform(x_aligned)
    proba = model.predict_proba(x_scaled)[0]
    classes = list(model.classes_)
    approval_probability = float(proba[classes.index(1)]) if 1 in classes else float(proba.max())
    return approval_probability >= APPROVAL_THRESHOLD, approval_probability


# ---------------------------------------------------------------------------
# 5. UI — input collection (native Streamlit components only)
# ---------------------------------------------------------------------------
def collect_user_inputs() -> dict[str, Any] | None:
    """Render the application form. Returns the input dict on submit, else None."""
    with st.form("loan_application", clear_on_submit=False):
        st.subheader("Loan Application Form")

        col_fin, col_pers, col_loan = st.columns(3)

        with col_fin:
            with st.container(border=True):
                st.markdown("**Financial Profile**")
                applicant_income = st.number_input(
                    "Applicant Income ($)", min_value=0.0, value=10_000.0, step=100.0, format="%.0f"
                )
                coapplicant_income = st.number_input(
                    "Coapplicant Income ($)", min_value=0.0, value=2_000.0, step=100.0, format="%.0f"
                )
                savings = st.number_input(
                    "Savings ($)", min_value=0.0, value=5_000.0, step=100.0, format="%.0f"
                )
                existing_loans = st.number_input(
                    "Existing Loans Count", min_value=0, max_value=10, value=1, step=1
                )

        with col_pers:
            with st.container(border=True):
                st.markdown("**Personal Profile**")
                age = st.slider("Age", 18, 100, 35)
                gender = st.selectbox("Gender", GENDER_OPTIONS)
                marital_status = st.selectbox("Marital Status", MARITAL_OPTIONS)
                dependents = st.selectbox("Dependents", DEPENDENTS_OPTIONS)
                education_level = st.selectbox("Education Level", EDUCATION_OPTIONS)
                employment_status = st.selectbox("Employment Status", EMPLOYMENT_OPTIONS)
                employer_category = st.selectbox("Employer Category", EMPLOYER_OPTIONS)

        with col_loan:
            with st.container(border=True):
                st.markdown("**Loan Details**")
                loan_amount = st.number_input(
                    "Loan Amount ($)", min_value=0.0, value=15_000.0, step=500.0, format="%.0f"
                )
                collateral_value = st.number_input(
                    "Collateral Value ($)", min_value=0.0, value=20_000.0, step=500.0, format="%.0f"
                )
                loan_term = st.selectbox("Loan Term (Months)", LOAN_TERM_OPTIONS)
                credit_score = st.slider("Credit Score", 300, 850, 650)
                dti_ratio = st.slider(
                    "Debt-to-Income Ratio (DTI)", 0.0, 1.0, 0.30, step=0.01, format="%.2f"
                )
                loan_purpose = st.selectbox("Loan Purpose", PURPOSE_OPTIONS)
                property_area = st.selectbox("Property Area", AREA_OPTIONS)

        submitted = st.form_submit_button("Predict Loan Approval", type="primary")

    if not submitted:
        return None

    return {
        "Applicant_Income": float(applicant_income),
        "Coapplicant_Income": float(coapplicant_income),
        "Savings": float(savings),
        "Collateral_Value": float(collateral_value),
        "Loan_Amount": float(loan_amount),
        "Existing_Loans": float(existing_loans),
        "Age": float(age),
        "Credit_Score": float(credit_score),
        "DTI_Ratio": float(dti_ratio),
        "Loan_Term": float(loan_term),
        "Dependents": DEPENDENTS_MAP[str(dependents)],
        "Gender": gender,
        "Marital_Status": marital_status,
        "Employment_Status": employment_status,
        "Loan_Purpose": loan_purpose,
        "Property_Area": property_area,
        "Education_Level": education_level,
        "Employer_Category": employer_category,
    }


def build_raw_frame(inputs: dict[str, Any]) -> pd.DataFrame:
    """Pack the raw user inputs into a single-row dataframe (notebook columns)."""
    return pd.DataFrame([inputs])


# ---------------------------------------------------------------------------
# 6. UI — results & sidebar
# ---------------------------------------------------------------------------
def render_results(
    approved: bool,
    probability: float,
    inputs: dict[str, Any],
    features: pd.DataFrame,
) -> None:
    """Decision banner, metric row and probability progress bar."""
    if approved:
        st.success("✅ LOAN APPROVED — the model recommends approving this application.")
    else:
        st.error("❌ LOAN REJECTED — the model recommends rejecting this application.")

    m1, m2, m3 = st.columns(3)
    m1.metric("Approval Probability", f"{probability:.1%}")
    m2.metric("Decision Threshold", f"{APPROVAL_THRESHOLD:.0%}")
    total_income = inputs["Applicant_Income"] + inputs["Coapplicant_Income"]
    loan_to_income = inputs["Loan_Amount"] / total_income if total_income > 0 else float("inf")
    m3.metric("Loan-to-Income", f"{loan_to_income:.2f}")

    st.progress(probability, text=f"Approval probability: {probability:.1%}")

    with st.expander("View the exact feature vector sent to the model"):
        st.dataframe(features.T.rename(columns={0: "value"}), use_container_width=True)
        st.caption(f"{features.shape[1]} features — Applicant_ID excluded, in training column order.")


def render_sidebar(source: str, warning: str | None) -> None:
    """Model metadata + fallback warnings in the sidebar."""
    st.sidebar.title("🏦 Loan Approval Model")

    st.sidebar.header("Model Metadata")
    for key, value in MODEL_METADATA.items():
        st.sidebar.markdown(f"- **{key}:** {value}")
    st.sidebar.metric("Reported Accuracy", MODEL_METADATA["Accuracy"])
    st.sidebar.divider()

    if source == "trained":
        st.sidebar.success(f"Trained artifacts loaded ({MODEL_FILE} + {SCALER_FILE}).")
    else:
        st.sidebar.warning(warning or "Fallback synthetic-data model is active.")
        st.sidebar.info(
            "The metadata above describes your original trained model. "
            "Fallback predictions are illustrative only."
        )


# ---------------------------------------------------------------------------
# 7. Main
# ---------------------------------------------------------------------------
def main() -> None:
    st.set_page_config(page_title="Loan Approval Prediction", page_icon="🏦", layout="wide")
    st.title("🏦 Loan Approval Prediction")
    st.caption(
        "Logistic Regression pipeline — StandardScaler + one-hot encoding "
        "identical to the training notebook."
    )

    model, scaler, source, warning = load_artifacts()
    render_sidebar(source, warning)

    inputs = collect_user_inputs()
    if inputs is None:
        st.info("Fill in the application form and press **Predict Loan Approval**.")
        return

    features = transform_raw_frame(build_raw_frame(inputs))
    approved, probability = predict_approval(model, scaler, features)
    render_results(approved, probability, inputs, features)


if __name__ == "__main__":
    main()
